# Generated by Django 2.2.3 on 2019-11-24 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodTypes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16, verbose_name='分类名')),
                ('ishaveChild', models.BooleanField(default=False, verbose_name='类目级别')),
            ],
            options={
                'verbose_name': '导航类型',
                'verbose_name_plural': '导航类型',
                'db_table': 'good_types',
            },
        ),
        migrations.CreateModel(
            name='GoodType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16, verbose_name='分类名')),
                ('imgurl', models.CharField(max_length=256, null=True, verbose_name='分类图片')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ClassifyList', to='goods.GoodTypes', verbose_name='父类目级别')),
            ],
            options={
                'verbose_name': '商品类型',
                'verbose_name_plural': '商品类型',
                'db_table': 'good_type',
            },
        ),
    ]
