# Generated by Django 2.2.3 on 2019-11-24 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_goods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='g_price',
            field=models.FloatField(default=0, verbose_name='价格'),
        ),
    ]
