# Generated by Django 2.2.3 on 2020-03-13 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20191123_0356'),
        ('goods', '0005_auto_20200228_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='isLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='关联商品id')),
                ('user_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='user.WxUser', verbose_name='关联用户id')),
            ],
            options={
                'verbose_name': '收藏',
                'verbose_name_plural': '收藏',
                'db_table': 'isLike',
            },
        ),
    ]
