# Generated by Django 2.2.3 on 2020-03-13 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_auto_20200313_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='islike',
            name='like',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='goodautoimg',
            name='parent_category',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='shopGoodsImageList', to='goods.GoodDetail', verbose_name='父类目级别'),
        ),
        migrations.AlterField(
            model_name='gooddetail',
            name='parent_category',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='父类目级别'),
        ),
    ]
