# Generated by Django 2.2.3 on 2020-03-14 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_auto_20200313_2011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'ordering': ['id'], 'verbose_name': '商品信息', 'verbose_name_plural': '商品信息'},
        ),
    ]
