# Generated by Django 2.2.3 on 2020-03-22 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_auto_20200314_1909'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='goods',
        #     name='g_details',
        # ),
        migrations.AlterField(
            model_name='goodautoimg',
            name='imgUrl',
            field=models.ImageField(max_length=2048, upload_to='', verbose_name='商品图片'),
        ),
        migrations.AlterField(
            model_name='gooddetail',
            name='imgUrl',
            field=models.ImageField(max_length=2048, upload_to='', verbose_name='商品图片'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='g_imgs',
            field=models.ImageField(max_length=1024, upload_to='', verbose_name='商品封面图'),
        ),
        migrations.AlterField(
            model_name='goodtype',
            name='imgurl',
            field=models.ImageField(max_length=256, null=True, upload_to='', verbose_name='分类图片'),
        ),
    ]
