# Generated by Django 2.2.3 on 2020-03-22 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0010_auto_20200322_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gooddetail',
            name='details',
            field=models.TextField(max_length=2048, verbose_name='详情图片'),
        ),
    ]
