# Generated by Django 2.2.3 on 2020-03-23 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0011_auto_20200322_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodautoimg',
            name='imgUrl',
            field=models.CharField(max_length=2048, verbose_name='商品图片'),
        ),
        migrations.AlterField(
            model_name='gooddetail',
            name='imgUrl',
            field=models.CharField(max_length=2048, verbose_name='商品图片'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='g_imgs',
            field=models.CharField(max_length=1024, verbose_name='商品封面图'),
        ),
        migrations.AlterField(
            model_name='goodtype',
            name='imgurl',
            field=models.CharField(max_length=256, null=True, verbose_name='分类图片'),
        ),
    ]
