# Generated by Django 2.2.3 on 2019-11-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavMenu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('menuName', models.CharField(max_length=16, unique=True, verbose_name='导航菜单')),
                ('n_img', models.CharField(max_length=256, verbose_name='菜单图片')),
            ],
            options={
                'verbose_name': '分类导航',
                'verbose_name_plural': '分类导航',
                'db_table': 'NavMenu',
            },
        ),
    ]
