# Generated by Django 2.2.3 on 2020-03-23 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0002_auto_20200322_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navmenu',
            name='n_img',
            field=models.CharField(max_length=256, verbose_name='菜单图片'),
        ),
    ]
