# Generated by Django 2.2.3 on 2019-11-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WxUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(blank=True, max_length=50, verbose_name='昵称')),
                ('user_avatar', models.ImageField(default='image/default.png', max_length=500, upload_to='static/uploads/%Y/%m/%d', verbose_name='用户头像')),
                ('user_phone', models.BigIntegerField(blank=True, null=True, verbose_name='手机号')),
                ('user_sex', models.SmallIntegerField(choices=[(0, '女'), (1, '男')], default=1, verbose_name='性别')),
                ('openid', models.CharField(max_length=50, unique=True, verbose_name='微信反馈id')),
                ('created_data', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': 'uers_info',
            },
        ),
    ]
