# Generated by Django 2.2.3 on 2019-11-22 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='wxuser',
            table='user_info',
        ),
    ]
