# Generated by Django 2.2.3 on 2019-11-23 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191122_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wxuser',
            name='user_avatar',
            field=models.CharField(max_length=500, verbose_name='用户头像'),
        ),
    ]
