# Generated by Django 2.2.3 on 2020-03-13 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20191123_0356'),
    ]

    operations = [
        migrations.AddField(
            model_name='wxuser',
            name='session_key',
            field=models.CharField(default='', max_length=50, verbose_name='session'),
        ),
        migrations.AddField(
            model_name='wxuser',
            name='uuid',
            field=models.CharField(default='', max_length=1024, verbose_name='自定义唯一标识'),
        ),
    ]
