# Generated by Django 2.2.3 on 2020-03-22 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200313_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wxuser',
            name='user_avatar',
            field=models.ImageField(max_length=500, upload_to='', verbose_name='用户头像'),
        ),
    ]
