# Generated by Django 2.2.3 on 2020-03-23 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200322_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wxuser',
            name='user_avatar',
            field=models.CharField(max_length=500, verbose_name='用户头像'),
        ),
    ]
