# Generated by Django 2.2.3 on 2020-03-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='b_img',
            field=models.ImageField(max_length=256, upload_to=''),
        ),
    ]
